name: Sync with HuggingFace Hub

on:
  push:
    branches: [huggingface-space] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with HuggingFace
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: leeeawa/freegpt-webui
        huggingface_repo_id: ileee/freegpt-webui
        repo_type: space
        space_sdk: docker
        hf_token: ${{ secrets.HF_TOKEN }}
        
